name: Docker App Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Build Docker image
        run: |
          docker build -t flask-app .
      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ secrets.GITHUB_REPOSITORY }}
          tag: latest
      - name: Create test report
        run: |
          pytest --junitxml=report.xml
