name: Docker App Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Build Docker image
        run: |
          docker build -t flask-app .
      - name: Push Docker image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ secrets.GITHUB_REPOSITORY }}
          tag: latest
      - name: Run static analysis
        run: |
          pylint app.py
      - name: Generate documentation
        run: |
          make docs
      - name: Create test report
        run: |
          pytest --junitxml=report.xml
