name: Docker App Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Build Docker image
        env: 
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME2 }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN2 }}
        run: |
          docker build -t flask-app -t ghcr.io/${{ github.repository }}/flask-app:latest .
          echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
          docker push ghcr.io/${{ github.repository }}/flask-app:latest
